name: CI [MacOS] beta

on: [workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install Brew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> ~/.zprofile
        eval $(/opt/homebrew/bin/brew shellenv)
    - name: Install Ngrok
      run: |
        brew install unzip
        brew install --cask ngrok
    - name: Adding New User
      run: |
        sudo su
        dscl . -create /Users/hakiraadityaa
        dscl . -create /Users/hakiraadityaa UserShell /bin/bash
        dscl . -create /Users/hakiraadityaa RealName "Hakira Aditya" 
        dscl . -create /Users/hakiraadityaa UniqueID "510"
        dscl . -create /Users/hakiraadityaa PrimaryGroupID 20
        dscl . -create /Users/hakiraadityaa NFSHomeDirectory /Users/hakiraadityaa
        dscl . -passwd /Users/hakiraadityaa admin321 
        dscl . -append /Groups/admin GroupMembership hakiraadityaa

    - name: Ngrok Auth
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ngrok authtoken $NGROK_AUTH_TOKEN
        ngrok tcp 22
